from langchain_core.prompts import PromptTemplate

CODE_FIXER_PROMPT = PromptTemplate.from_template(
    "<|im_start|>system\n"
    "Convert OCR text to clean code. No talk. No markdown. No objects.\n"
    "<|im_end|>\n"
    "<|im_start|>user\n"
    "OCR Text: {ocr_output}\n\n"
    "Fixed Code:\n"
    "<|im_end|>\n"
    "<|im_start|>assistant\n"
    # "<|im_start|>system\n"
    # "You are a code OCR correction tool. Output ONLY the code logic. "
    # "No talk, no backticks, no markdown. Stop immediately after the code."
    # "You are a code OCR correction tool. "
    # "Your task is to fix syntax errors and "
    # "indentation in the provided text. \n"
    # "CRITICAL RULES:\n"
    # "1. Do NOT add imports that aren't in the input.\n"
    # "2. Do NOT add explanations or markdown formatting.\n"
    # "3. Keep the logic exactly as provided, "
    # "only fix the characters and formatting.\n"
    # "4. Fix the syntax errors, correct misread characters "
    # "(like '5' instead of 's'), and ensure proper indentation. "
    # "<|im_end|>"
    # "<|im_start|>user"
    # "Correct this OCR text:"
    # "{ocr_output}<|im_end|>"
    # "<|im_start|>assistant"
)
