services:
  mongodb:
    image: mongo:7.0
    container_name: code_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=emy
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          memory: 4G

volumes:
  mongo_data:
